export const OPERATE_DASHBOARD_LOADING = "OPERATE_DASHBOARD_LOADING";
export const OPERATE_DASHBOARD_SUCCESS = "OPERATE_DASHBOARD_SUCCESS";
export const OPERATE_DASHBOARD_ERROR = "OPERATE_DASHBOARD_ERROR";